
- name: add user 
  hosts: localhost,sys
  vars:
    username: archo5
  tasks:
    - name: add user 
      user: 
        name: "{{username}}"
        generate_ssh_key: yes
        groups: wheel
        #state: absent
        #remove: yes
      register: newuser
      become: yes 
      tags:
        - user

    - name: wheel group to NOPASSWD
      shell: sed -i 's/^#\s*\(%wheel\s*ALL=(ALL)\s*NOPASSWD:\s*ALL\)/\1/' /etc/sudoers
      become: yes
      tags:
        - sudoer

    - name: register ssh public key (self)
      authorized_key:
        user: "{{username}}"
        key: "{{ newuser.ssh_public_key }}"
        #state: absent
      become: yes 
      tags:
        - auth 

    - name: cat pub key 
      shell: "cat ~/.ssh/id_rsa.pub" 
      register: out
      become: yes
      become_user: "{{username}}"
      delegate_to: localhost
      tags:
        - pub

    - name: register ssh public key 
      authorized_key:
        user: "{{username}}"
        key: "{{ out.stdout }}"
        #state: absent
      become: yes
      tags:
        - pub



